version: "3"
services:
  database:
    image: mysql:5.6
    platform: linux/amd64
    container_name: database
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306/tcp"
    expose:
      - "3306"
    volumes:
      - ./docker/db/sql-scripts:/docker-entrypoint-initdb.d

    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=db
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=mysql
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"status", "-h", "localhost", "-u", "mysql", "-pmysql" ]
      interval: 5s
      timeout: 10s
      retries: 20